GET http://localhost:5000/api/phones HTTP/1.1

###
GET http://localhost:5000/api/phones/2 HTTP/1.1

###
POST http://localhost:5000/api/phones HTTP/1.1
Content-Type: application/json

{
  "model": "Xiaomi",
  "brand": "Note 9",
  "manufacturedYear": 2020,
  "RAMsize": 8,
  "CPUname": "MediaTek Helio G85",
  "screenDiagonal": 6.5,
  "isNFC": true,
  "CPU_id": 4
}

###
PATCH http://localhost:5000/api/phones/5 HTTP/1.1
Content-Type: application/json 

{
  "manufacturedYear": 2014
}

###
PUT http://localhost:5000/api/phones/6 HTTP/1.1
Content-Type: application/json 

{
  "model": "Samsung",
  "brand": "Galaxy Z Flip",
  "manufacturedYear": 2021,
  "RAMsize": 32,
  "CPUname": "Qualcomm Snapdragon",
  "screenDiagonal": 6.7,
  "isNFC": true,
  "CPU_id": 2
}

###
DELETE http://localhost:5000/api/phones/2

